version: "3"
services:
    web:
        image: nginx:latest
        container_name: key-manager-web
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: key-manager-php
        volumes:
            - .:/var/www/html
        environment:
            DB_CONNECTION: mysql
            DB_HOST: key-manager-db
            DB_PORT: 3306
            DB_DATABASE: key_manager
            DB_USERNAME: root
            DB_PASSWORD: bakugan903
            MAIL_MAILER: smtp
            MAIL_HOST: mailhog
            MAIL_PORT: 1025
            MAIL_USERNAME: null
            MAIL_PASSWORD: null
            MAIL_ENCRYPTION: null
            MAIL_FROM_ADDRESS: "hello@example.com"
            MAIL_FROM_NAME: "${APP_NAME}"
    db:
        image: mysql:8.0
        container_name: key-manager-db
        environment:
            MYSQL_ROOT_PASSWORD: bakugan903
            MYSQL_DATABASE: key_manager
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: key-manager-phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: key-manager-db
            MYSQL_ROOT_PASSWORD: bakugan903
    mailhog:
        image: mailhog/mailhog
        container_name: key-manager-mailhog
        ports:
            - "8025:8025"
