<script setup>
import { onMounted } from "vue";
import AppLayout from "@/Layouts/AppLayout.vue";
import { Link, usePage } from "@inertiajs/inertia-vue3";
import GatesWidget from "./Widgets/GatesWidget.vue";
import VirtualKeysWidget from "./Widgets/VirtualKeysWidget.vue";
import UsersWidget from "./Widgets/UsersWidget.vue";
import EventsWidget from "./Widgets/EventsWidget.vue";
import HomeHeader from "../Components/Home/HomeHeader.vue";
import VirtualTicketsWidget from "./Widgets/VirtualTicketsWidget.vue";
import introJs from "intro.js";

onMounted(() => {
  const user = usePage().props.value.user;
  if (user.tours?.dashboard === true) {
    return;
  }

  let tour = introJs();
  tour.setOptions({
    steps: [
      {
        title: `Welcome to Key Manager! 👋`,
        intro: `Let me show you around the Dashboard! It'll be quick, I promise!`,
        element: document.querySelector("#dashboard"),
      },
      {
        // intro: `You should start from adding your first gate by clicking "Add Gate" button and completing form`,
        title: `Here is the list of Gates! 🔒`,
        intro: `You can start from adding your first gate by clicking "Add Gate" button and completing the form`,
        element: document.querySelector("#firstStepTour"),
      },
      {
        title: `See your Virtual Key Box! 🔑`,
        // intro: `Then you can give yourself and your teammates access to previously added gates by creating Virtual Keys`,
        intro: `Later on you can give yourself and your teammates access to the Gates by creating Virtual Keys`,
        element: document.querySelector("#secondStepTour"),
      },
      {
        title: `The list of Events! 🗓️`,
        intro: `
        Finally here you can see Events that will be generated by interactions with the Gate`,
        element: document.querySelector("#thirdStepTour"),
      },
      {
        title: `Virtual Tickets! 🎫`,
        intro: `If you want to give access to your gates by sharing time limited qr code via e-mail you can also create Virtual Ticket available here or in "Virtual Tickets" card`,
      },
    ],
  });
  tour.onexit(() => {
    axios.put(`/tours`, { tour: `dashboard` });
  });

  tour.start();
});
</script>

<template>
  <AppLayout title="Dashboard">
    <template #header>
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        Dashboard
      </h2>
    </template>
    <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="parent gap-x-5 gap-y-5">
          <GatesWidget
            class="max-h-100 area1"
            v-bind:attrs="attrs"
            id="firstStepTour"
          />
          <UsersWidget class="max-h-100 area2" v-bind:attrs="attrs" />
          <transition name="slide" mode="out-in">
                        <VirtualKeysWidget
                            v-if="showKeyList"
                            class="max-h-100 area3"
                            v-bind:attrs="attrs"
                            v-on:switch="switchKeyList"
                            id="secondStepTour"
                        />
                    </transition>

                    <transition name="slide" mode="out-in">
                        <VirtualTicketsWidget
                            v-if="!showKeyList"
                            class="max-h-100 area3"
                            v-bind:attrs="attrs"
                            v-on:switch="switchKeyList"
                        />
                    </transition>
          <EventsWidget
            id="thirdStepTour"
            class="max-h-200 area4"
            v-bind:attrs="attrs"
          />
        </div>
      </div>
    </div>
  </AppLayout>
</template>

<script>
import GateShow from "./Gates/Show.vue";
import CreateGateForm from "./Gates/Partials/CreateGateForm.vue";

export default {
    components: {
        GateShow,
        CreateGateForm,
    },
    data() {
        return {
            showKeyList: true,
            component: "GateShow",
            attrs: this.$attrs,
        };
    },
    methods: {
        switchKeyList() {
            this.showKeyList = !this.showKeyList;
        },
        toggle() {
            if (this.component === "GateShow") {
                this.component = "CreateGateForm";
            } else {
                this.component = "GateShow";
            }
        },
    },
  },
};
</script>

<style>
@media only screen and (min-width: 100px) {
  .parent {
    display: grid;
    grid-template-columns: 1fr;
    grid-template-rows: repeat(4, 1fr);
  }

  .area1 {
    grid-area: 1 / 1 / 2 / 2;
  }
  .area2 {
    grid-area: 2 / 1 / 3 / 2;
  }
  .area3 {
    grid-area: 3 / 1 / 4 / 2;
  }
  .area4 {
    grid-area: 4 / 1 / 5 / 2;
  }
}

@media only screen and (min-width: 650px) {
  .parent {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    grid-template-rows: repeat(2, 1fr);
  }

  .area1 {
    grid-area: 1 / 1 / 2 / 2;
  }
  .area2 {
    grid-area: 2 / 1 / 3 / 2;
  }
  .area3 {
    grid-area: 1 / 2 / 2 / 3;
  }
  .area4 {
    grid-area: 2 / 2 / 3 / 3;
  }
}

@media only screen and (min-width: 1250px) {
  .parent {
    display: grid;
    grid-template-columns: 0.8fr 1fr 1.1fr;
    grid-template-rows: repeat(2, 1fr);
  }

  .area1 {
    grid-area: 1 / 1 / 2 / 2;
  }
  .area2 {
    grid-area: 1 / 2 / 2 / 3;
  }
  .area3 {
    grid-area: 2 / 1 / 3 / 3;
  }
  .area4 {
    grid-area: 1 / 3 / 3 / 4;
  }
}
.slide-enter-active,
.slide-leave-active {
    transition: all 0.3s ease;
}

.slide-enter-from,
.slide-leave-to {
    transform: translate(-10px, 10px);
    opacity: 0;
}
</style>
